-- ============================================================
-- SEED: maths_content
-- Reference material for all 38 Maths skills
-- Types: concept | worked_example | common_error | formula |
--        mnemonic | definition
-- Pattern: insert ... select id from maths_skills where skill_ref = '...'
-- ============================================================

-- ══════════════════════════════════════════════════════════════
-- MICHAELMAS 1
-- ══════════════════════════════════════════════════════════════

-- MA1-01: Bounds
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Upper and lower bounds arise when a measurement has been rounded. A value x rounded to the nearest unit d has lower bound x − d/2 (inclusive) and upper bound x + d/2 (exclusive). The bounds represent the range of possible exact values before rounding.' from public.maths_skills where skill_ref = 'MA1-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'LB = x − d/2, UB = x + d/2, where d is the degree of rounding. For calculations: max sum = UB₁ + UB₂; max difference = UB₁ − LB₂; max product = UB₁ × UB₂; max quotient = UB₁ ÷ LB₂.' from public.maths_skills where skill_ref = 'MA1-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'A length is given as 6.4 cm (1 d.p.). d = 0.1, so LB = 6.35 cm, UB = 6.45 cm. A second length is 3.2 cm (1 d.p.): LB = 3.15 cm, UB = 3.25 cm. Maximum possible sum = 6.45 + 3.25 = 9.70 cm. Minimum possible sum = 6.35 + 3.15 = 9.50 cm.' from public.maths_skills where skill_ref = 'MA1-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Writing UB = 6.44 for a value rounded to 1 d.p. instead of 6.45. The upper bound is 6.45 — it is the smallest value that would round up to 6.5, not the largest value that rounds to 6.4. Always add half the degree of rounding.' from public.maths_skills where skill_ref = 'MA1-01';

-- MA1-02: Recurring decimals to fractions proof
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Any recurring decimal can be expressed exactly as a fraction. Let x equal the decimal, multiply by 10ⁿ where n is the number of digits in the repeating block (to shift one full cycle), then subtract the original equation to eliminate the recurring part and solve for x.' from public.maths_skills where skill_ref = 'MA1-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Convert 0.363636... to a fraction. Let x = 0.363636... The repeating block has 2 digits, so multiply by 100: 100x = 36.363636... Subtract: 99x = 36, so x = 36/99 = 4/11. Check: 4 ÷ 11 = 0.363636... ✓. For 0.7̄ (one repeating digit): 10x = 7.777..., subtract x = 0.777..., so 9x = 7, x = 7/9.' from public.maths_skills where skill_ref = 'MA1-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Multiplying by the wrong power of 10 — always multiply by 10ⁿ where n is the length of the repeating block only, not the total number of decimal places. For 0.136363... the non-repeating part is 0.1; let x = 0.136363..., then 10x = 1.36363... and 1000x = 136.363...; subtract to get 990x = 135.' from public.maths_skills where skill_ref = 'MA1-02';

-- MA1-03: Pythagoras' Theorem
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'In any right-angled triangle, the square on the hypotenuse equals the sum of the squares on the other two sides. The hypotenuse is always the longest side and is always opposite the right angle. Use this theorem to find any side when the other two sides are known.' from public.maths_skills where skill_ref = 'MA1-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'a² + b² = c², where c is the hypotenuse. To find the hypotenuse: c = √(a² + b²). To find a shorter side: a = √(c² − b²).' from public.maths_skills where skill_ref = 'MA1-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Find the hypotenuse of a right-angled triangle with legs 5 cm and 12 cm: c² = 5² + 12² = 25 + 144 = 169, c = 13 cm. Find a missing leg: hypotenuse = 10 cm, one leg = 6 cm. Missing leg = √(10² − 6²) = √(100 − 36) = √64 = 8 cm.' from public.maths_skills where skill_ref = 'MA1-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Adding the squares to find a shorter side instead of subtracting. Always identify which side is the hypotenuse first (it is opposite the right angle). If finding the hypotenuse, add the squares; if finding a leg, subtract the known leg''s square from the hypotenuse''s square.' from public.maths_skills where skill_ref = 'MA1-03';

-- MA1-04: Trigonometry
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'In a right-angled triangle, the three trigonometric ratios link an angle to two sides. The sides are named relative to the chosen angle: opposite (O) is across from it, adjacent (A) is next to it, and hypotenuse (H) is always opposite the right angle.' from public.maths_skills where skill_ref = 'MA1-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'SOH-CAH-TOA: sin θ = O/H, cos θ = A/H, tan θ = O/A. To find a side: multiply. To find an angle: use the inverse trig function (sin⁻¹, cos⁻¹, tan⁻¹).' from public.maths_skills where skill_ref = 'MA1-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Find angle θ in a right-angled triangle where adjacent = 7 cm and hypotenuse = 14 cm. Use cos: cos θ = 7/14 = 0.5, θ = cos⁻¹(0.5) = 60°. Find a side: angle = 35°, hypotenuse = 9 cm, find opposite. sin 35° = O/9, O = 9 × sin 35° ≈ 5.16 cm.' from public.maths_skills where skill_ref = 'MA1-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Mislabelling opposite and adjacent — these depend on which angle you are working with, not the shape of the triangle. The hypotenuse is always the same, but O and A swap when you switch to the other acute angle. Always label the sides relative to the angle in the question.' from public.maths_skills where skill_ref = 'MA1-04';

-- MA1-05: Pythagoras and Trig in 3D
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'To find distances or angles in 3D shapes, identify a right-angled triangle within the 3D figure, then apply Pythagoras'' theorem or trigonometry to that 2D cross-section. Common shapes are cuboids, square-based pyramids, and triangular prisms. Always sketch the triangle you plan to use.' from public.maths_skills where skill_ref = 'MA1-05';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Find the space diagonal of a cuboid 4 cm × 3 cm × 2 cm. Step 1: base face diagonal = √(4² + 3²) = √25 = 5 cm. Step 2: use this diagonal and the height as legs of a new right-angled triangle: space diagonal = √(5² + 2²) = √29 ≈ 5.39 cm.' from public.maths_skills where skill_ref = 'MA1-05';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Trying to apply Pythagoras directly in 3D without first reducing to a 2D right-angled triangle. Always work in two stages: find the base diagonal first, then use it to find the space diagonal. Label and sketch each triangle clearly.' from public.maths_skills where skill_ref = 'MA1-05';

-- MA1-06: Expanding double brackets
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'To expand two brackets, multiply each term in the first bracket by each term in the second bracket. Using FOIL (First, Outer, Inner, Last) ensures all four products are found. Collect like terms after multiplying.' from public.maths_skills where skill_ref = 'MA1-06';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Expand (x + 3)(x − 2): F: x × x = x²; O: x × (−2) = −2x; I: 3 × x = 3x; L: 3 × (−2) = −6. Result: x² − 2x + 3x − 6 = x² + x − 6. Expand (2x − 1)(3x + 4): 6x² + 8x − 3x − 4 = 6x² + 5x − 4.' from public.maths_skills where skill_ref = 'MA1-06';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Forgetting to multiply the last terms together, producing x² + x instead of x² + x − 6. Also, sign errors when a bracket contains subtraction — always carry the negative sign with the term: (x − 2) means the second term is −2, not +2.' from public.maths_skills where skill_ref = 'MA1-06';

-- MA1-07: Factorising to single brackets
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Factorising to a single bracket is the reverse of expanding. Find the highest common factor (HCF) of all terms in the expression and place it outside the bracket. Each term inside the bracket is the original term divided by the HCF.' from public.maths_skills where skill_ref = 'MA1-07';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Factorise 12x³ − 8x²: HCF of 12x³ and 8x² is 4x². Answer: 4x²(3x − 2). Check by expanding: 4x² × 3x = 12x³, 4x² × (−2) = −8x². ✓. Factorise 5ab + 15b²: HCF = 5b. Answer: 5b(a + 3b).' from public.maths_skills where skill_ref = 'MA1-07';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Taking out only a numerical factor and ignoring a common variable factor, or taking out a factor that is not common to every term. Always check your answer by expanding back — if it does not give the original expression, the factorisation is wrong.' from public.maths_skills where skill_ref = 'MA1-07';

-- MA1-08: Factorising quadratic expressions
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'To factorise x² + bx + c, find two integers p and q such that p × q = c and p + q = b. Write the result as (x + p)(x + q). For ax² + bx + c with a ≠ 1, find two numbers that multiply to a × c and sum to b, then split the middle term and factorise in pairs.' from public.maths_skills where skill_ref = 'MA1-08';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Factorise x² + 5x + 6: need two numbers multiplying to 6 and adding to 5 → 2 and 3. Answer: (x + 2)(x + 3). Factorise x² − x − 6: multiply to −6 and add to −1 → −3 and +2. Answer: (x − 3)(x + 2). Always check by expanding.' from public.maths_skills where skill_ref = 'MA1-08';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Sign errors — when c is negative, one factor is positive and one is negative. When c is positive and b is negative, both factors are negative. Write out the factor pairs systematically and check their sum before writing the final answer. Always re-expand to verify.' from public.maths_skills where skill_ref = 'MA1-08';

-- ══════════════════════════════════════════════════════════════
-- MICHAELMAS 2
-- ══════════════════════════════════════════════════════════════

-- MA2-01: Indices — laws and review
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'The index laws allow us to simplify expressions involving powers of the same base. There are five key laws: multiply (add indices), divide (subtract indices), power of a power (multiply indices), zero index equals 1, and power of a product splits across each factor.' from public.maths_skills where skill_ref = 'MA2-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'aᵐ × aⁿ = aᵐ⁺ⁿ; aᵐ ÷ aⁿ = aᵐ⁻ⁿ; (aᵐ)ⁿ = aᵐⁿ; a⁰ = 1 (a ≠ 0); (ab)ⁿ = aⁿbⁿ.' from public.maths_skills where skill_ref = 'MA2-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Simplify 3⁴ × 3² = 3⁶ = 729. Simplify (2³)⁴ = 2¹² = 4096. Simplify 5⁷ ÷ 5⁴ = 5³ = 125. Simplify (2x²)³ = 2³ × x⁶ = 8x⁶. Any base to the power 0: 7⁰ = 1, (−3)⁰ = 1.' from public.maths_skills where skill_ref = 'MA2-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Multiplying the bases as well as adding the indices: writing 3² × 3³ = 9⁵ instead of 3⁵. The base stays fixed; only the exponent changes. Also confusing (ab)ⁿ with aⁿ + bⁿ — the power distributes as a product, not a sum.' from public.maths_skills where skill_ref = 'MA2-01';

-- MA2-02: Indices — negative and fractional
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'A negative index means the reciprocal: a⁻ⁿ = 1/aⁿ. A fractional index means a root: a^(1/n) = ⁿ√a (the denominator is the root). When both numerator and denominator are present, the denominator is the root and the numerator is the power: a^(m/n) = (ⁿ√a)ᵐ.' from public.maths_skills where skill_ref = 'MA2-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'a⁻ⁿ = 1/aⁿ. a^(1/n) = ⁿ√a. a^(m/n) = (ⁿ√a)ᵐ. Apply root first, then power — avoids large numbers.' from public.maths_skills where skill_ref = 'MA2-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Evaluate 8^(2/3): cube root of 8 = 2, then square: 2² = 4. Evaluate 4^(−3/2): reciprocal of 4^(3/2). 4^(3/2) = (√4)³ = 2³ = 8, so 4^(−3/2) = 1/8. Evaluate 27^(−1/3) = 1/∛27 = 1/3.' from public.maths_skills where skill_ref = 'MA2-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Applying the power before the root for a^(m/n): computing 8² = 64 before taking the cube root makes the arithmetic harder. Always take the root first. Also, a negative index means reciprocal — it does not make the answer negative.' from public.maths_skills where skill_ref = 'MA2-02';

-- MA2-03: Plotting straight line graphs
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'To plot a straight line graph, substitute at least three x-values into the equation, calculate the corresponding y-values, plot the coordinate pairs, and join them with a ruled straight line. Using three points (rather than two) lets you check for arithmetic errors.' from public.maths_skills where skill_ref = 'MA2-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Plot y = 3x − 2 for −1 ≤ x ≤ 3. Table of values: x = −1 → y = −5; x = 0 → y = −2; x = 1 → y = 1; x = 3 → y = 7. Plot (−1, −5), (0, −2), (1, 1), (3, 7) and join with a straight line. The y-intercept is (0, −2) and gradient is 3 (rise 3 for every 1 unit right).' from public.maths_skills where skill_ref = 'MA2-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Using only two points to draw the line — if one has an arithmetic error the line will be completely wrong. Always compute three points and check they are collinear (lie on the same straight line) before drawing.' from public.maths_skills where skill_ref = 'MA2-03';

-- MA2-04: y = mx + c
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'In the equation y = mx + c, m is the gradient (steepness and direction of the line) and c is the y-intercept (the y-value where the line crosses the y-axis). The gradient can be found from any two points on the line as the change in y divided by the change in x.' from public.maths_skills where skill_ref = 'MA2-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Gradient m = (y₂ − y₁) / (x₂ − x₁). Equation of a line through point (x₁, y₁) with gradient m: y − y₁ = m(x − x₁), which rearranges to y = mx + c.' from public.maths_skills where skill_ref = 'MA2-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Find the equation of the line through (2, 5) and (6, 13). Gradient: m = (13 − 5)/(6 − 2) = 8/4 = 2. Using point (2, 5): y − 5 = 2(x − 2) → y = 2x + 1. Check with (6, 13): 2(6) + 1 = 13 ✓.' from public.maths_skills where skill_ref = 'MA2-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Writing the gradient upside-down as Δx/Δy instead of Δy/Δx. Gradient is always rise over run — how much y changes per unit of x. Also, forgetting to substitute a point back in to find c after determining m.' from public.maths_skills where skill_ref = 'MA2-04';

-- MA2-05: Parallel and perpendicular line equations
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Parallel lines never meet and always have equal gradients. Perpendicular lines meet at a right angle; their gradients are negative reciprocals of each other, meaning the product of the two gradients equals −1.' from public.maths_skills where skill_ref = 'MA2-05';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Parallel: m₁ = m₂. Perpendicular: m₁ × m₂ = −1, so m₂ = −1/m₁ (flip and change sign).' from public.maths_skills where skill_ref = 'MA2-05';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Line L₁: y = 4x − 3 (gradient 4). Parallel line through (1, 7): gradient = 4, so y − 7 = 4(x − 1) → y = 4x + 3. Perpendicular line through (1, 7): gradient = −1/4, so y − 7 = −¼(x − 1) → y = −x/4 + 29/4.' from public.maths_skills where skill_ref = 'MA2-05';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Taking only the reciprocal (flipping) but forgetting to change the sign, or changing the sign but not flipping. Both steps are needed for perpendicularity. The product of perpendicular gradients must equal −1 — use this to check your answer.' from public.maths_skills where skill_ref = 'MA2-05';

-- MA2-06: Mid-point of a line segment
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'The mid-point of a line segment is the point exactly halfway between its two endpoints. It is found by averaging the x-coordinates and averaging the y-coordinates of the two endpoints.' from public.maths_skills where skill_ref = 'MA2-06';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Mid-point M = ((x₁ + x₂)/2, (y₁ + y₂)/2).' from public.maths_skills where skill_ref = 'MA2-06';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Mid-point of (3, −1) and (7, 5): M = ((3+7)/2, (−1+5)/2) = (10/2, 4/2) = (5, 2). If one endpoint is (2, 6) and the mid-point is (5, 4), find the other endpoint: x = 2×5 − 2 = 8, y = 2×4 − 6 = 2. Other endpoint: (8, 2).' from public.maths_skills where skill_ref = 'MA2-06';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Subtracting coordinates instead of adding them before halving, giving the half-difference instead of the mid-point. Also, when finding a missing endpoint given the mid-point, students must multiply the mid-point coordinate by 2 and subtract the known endpoint.' from public.maths_skills where skill_ref = 'MA2-06';

-- MA2-07: Length of a line segment using Pythagoras
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'The distance between two points is found by treating the horizontal and vertical separations as the two legs of a right-angled triangle, then applying Pythagoras'' theorem to find the hypotenuse (the distance).' from public.maths_skills where skill_ref = 'MA2-07';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'd = √((x₂ − x₁)² + (y₂ − y₁)²). The order of subtraction does not matter because the differences are squared.' from public.maths_skills where skill_ref = 'MA2-07';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Distance from (1, 2) to (7, 10): Δx = 6, Δy = 8. d = √(6² + 8²) = √(36 + 64) = √100 = 10. Distance from (−2, 3) to (4, −5): Δx = 6, Δy = −8. d = √(36 + 64) = 10.' from public.maths_skills where skill_ref = 'MA2-07';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Adding the differences before squaring — computing √(Δx + Δy) instead of √(Δx² + Δy²). The differences must be squared individually first, then added, then square-rooted. This is the most common error in this topic.' from public.maths_skills where skill_ref = 'MA2-07';

-- MA2-08: Cumulative frequency graphs
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'A cumulative frequency graph (ogive) plots the running total of frequencies against the upper class boundary. It allows us to estimate the median (Q2), lower quartile (Q1), upper quartile (Q3), and interquartile range (IQR = Q3 − Q1) from grouped data.' from public.maths_skills where skill_ref = 'MA2-08';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'For n = 80 data points: median at cumulative frequency 40, Q1 at 20, Q3 at 60. Go horizontally from the y-axis at these values to the curve, then vertically down to the x-axis to read the estimates. IQR = Q3 − Q1. Points are plotted at the upper class boundary of each interval.' from public.maths_skills where skill_ref = 'MA2-08';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Plotting points at the midpoint of each class interval rather than the upper class boundary. The cumulative frequency represents data up to and including the upper boundary, so all points must be plotted at the upper boundary.' from public.maths_skills where skill_ref = 'MA2-08';

-- ══════════════════════════════════════════════════════════════
-- LENT 1
-- ══════════════════════════════════════════════════════════════

-- LT1-01: Percentages — increase and decrease
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'To increase or decrease a quantity by a percentage, multiply by a decimal multiplier. This is faster and less error-prone than finding the percentage separately and adding/subtracting.' from public.maths_skills where skill_ref = 'LT1-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Multiplier for p% increase = 1 + p/100. Multiplier for p% decrease = 1 − p/100.' from public.maths_skills where skill_ref = 'LT1-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Increase £350 by 12%: multiplier = 1.12. £350 × 1.12 = £392. Decrease £480 by 35%: multiplier = 0.65. £480 × 0.65 = £312. Two successive changes: increase by 20% then decrease by 20%: 1.20 × 0.80 = 0.96 — a net 4% decrease (not zero).' from public.maths_skills where skill_ref = 'LT1-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Thinking two successive equal percentage increases and decreases cancel out. A 20% increase followed by a 20% decrease gives 0.96 of the original — a 4% net loss — because the decrease is applied to the larger increased amount.' from public.maths_skills where skill_ref = 'LT1-01';

-- LT1-02: Percentages — reverse
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'A reverse percentage problem gives the value after a percentage change and asks for the original value. The key insight is that the given value equals the original multiplied by the multiplier, so divide by the multiplier to reverse the operation.' from public.maths_skills where skill_ref = 'LT1-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'A jacket costs £68 after a 15% reduction. The sale price represents 85% of the original, so the multiplier was 0.85. Original price = £68 ÷ 0.85 = £80. Check: £80 × 0.85 = £68 ✓. A price after a 20% increase is £156. Original = £156 ÷ 1.20 = £130.' from public.maths_skills where skill_ref = 'LT1-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Subtracting p% of the given price to find the original — this treats the given price as the original. The given price is already the result of the percentage change; you must divide by the multiplier, not subtract a percentage of the given value.' from public.maths_skills where skill_ref = 'LT1-02';

-- LT1-03: Percentages — change and profit/loss
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Percentage change measures the relative size of a change compared to the original value. Profit is a positive change; loss is a negative change. The denominator is always the original (starting) value, never the new value.' from public.maths_skills where skill_ref = 'LT1-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', '% change = (new value − original value) / original value × 100. % profit = profit / cost price × 100.' from public.maths_skills where skill_ref = 'LT1-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'A bike is bought for £250 and sold for £310. Profit = £60. % profit = 60/250 × 100 = 24%. A TV bought for £400 is sold for £340. Loss = £60. % loss = 60/400 × 100 = 15%.' from public.maths_skills where skill_ref = 'LT1-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Dividing by the new value rather than the original. Percentage change is always relative to where you started. Also, forgetting to multiply by 100 to express as a percentage.' from public.maths_skills where skill_ref = 'LT1-03';

-- LT1-04: Compound interest and depreciation
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Compound interest applies interest to the accumulated total (principal + previous interest) each period, so the amount grows faster than with simple interest. Depreciation is the same process in reverse — the value decreases by a fixed percentage each year.' from public.maths_skills where skill_ref = 'LT1-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Compound interest: A = P(1 + r/100)ⁿ, where P is principal, r is annual rate %, n is number of years. Depreciation: A = P(1 − r/100)ⁿ.' from public.maths_skills where skill_ref = 'LT1-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', '£5000 invested at 4% compound interest for 3 years: A = 5000 × 1.04³ = 5000 × 1.124864 ≈ £5624.32. A car worth £12000 depreciates at 18% per year for 2 years: A = 12000 × 0.82² = 12000 × 0.6724 ≈ £8068.80.' from public.maths_skills where skill_ref = 'LT1-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Using simple interest (P × r × n / 100) instead of compound interest. In compound interest the multiplier is raised to the power n — multiplying by (1.04 × n) is simple interest, not compound. Always use the exponent.' from public.maths_skills where skill_ref = 'LT1-04';

-- LT1-05: Solving inequalities
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Linear inequalities are solved using the same inverse operations as equations, with one critical difference: multiplying or dividing both sides by a negative number reverses the direction of the inequality sign. Solutions can be shown as an inequality, on a number line, or as a set.' from public.maths_skills where skill_ref = 'LT1-05';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Solve 4x − 3 ≥ 13: 4x ≥ 16, x ≥ 4. Solve −3x < 12: divide by −3 and flip the sign: x > −4. Solve 2 < 3x + 8 ≤ 17 (double inequality): subtract 8: −6 < 3x ≤ 9; divide by 3: −2 < x ≤ 3. On a number line: open circle at −2, closed circle at 3.' from public.maths_skills where skill_ref = 'LT1-05';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Forgetting to reverse the inequality sign when multiplying or dividing by a negative number. This is the most common error in this topic. If you rearrange to avoid dividing by a negative (e.g. add 3x to both sides before dividing), you eliminate the risk entirely.' from public.maths_skills where skill_ref = 'LT1-05';

-- LT1-06: Graphing inequalities
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'An inequality in two variables represents a half-plane (a region on one side of a boundary line). Draw the boundary line using y = ...: solid for ≤ or ≥, dashed for < or >. Then test a point (usually the origin) to determine which region to shade. In exam questions, the required region is usually left unshaded.' from public.maths_skills where skill_ref = 'LT1-06';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Show the region satisfying y ≤ 2x + 1, y > x − 2, x ≥ 0. Draw y = 2x + 1 (solid), y = x − 2 (dashed), x = 0 (solid). Test (1, 0): 0 ≤ 3 ✓, 0 > −1 ✓, 1 ≥ 0 ✓ — so (1, 0) is in the required region. Shade everywhere outside the required region.' from public.maths_skills where skill_ref = 'LT1-06';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Drawing a solid boundary for a strict inequality (< or >) or a dashed line for ≤ or ≥. Also, shading the wrong region — always test a specific point and verify each inequality to determine the correct side before shading.' from public.maths_skills where skill_ref = 'LT1-06';

-- LT1-07: Two-way tables
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'A two-way table organises data for two categorical variables. Each cell shows the frequency for a specific combination of categories. Row totals, column totals, and the grand total all provide constraints that can be used to find missing values.' from public.maths_skills where skill_ref = 'LT1-07';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', '60 students surveyed about sport preference (football or tennis) and gender. Totals: 35 male, 25 female. 20 males prefer football. Complete the table: males-tennis = 35−20 = 15; females-football = total football − 20; etc. Use the grand total and marginal totals to fill in all missing values systematically.' from public.maths_skills where skill_ref = 'LT1-07';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Confusing the grand total with a row/column total, or failing to use all the constraints. Work from cells you can calculate directly (a row or column with only one missing value) and fill the table step by step, checking that all rows and columns sum correctly.' from public.maths_skills where skill_ref = 'LT1-07';

-- LT1-08: Set notation
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Set notation describes relationships between collections of elements. The universal set ξ contains all elements under consideration. A ∪ B is the union (all elements in A or B or both). A ∩ B is the intersection (elements in both A and B). A'' is the complement of A (elements in ξ but not A).' from public.maths_skills where skill_ref = 'LT1-08';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'n(A ∪ B) = n(A) + n(B) − n(A ∩ B). This avoids double-counting elements in the intersection.' from public.maths_skills where skill_ref = 'LT1-08';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'ξ = {1,2,3,4,5,6,7,8}, A = {2,4,6,8}, B = {1,2,3,4}. A ∪ B = {1,2,3,4,6,8}, n = 6. A ∩ B = {2,4}, n = 2. A'' = {1,3,5,7}. Check: n(A∪B) = 4+4−2 = 6 ✓. (A ∩ B)'' = {1,3,5,6,7,8}.' from public.maths_skills where skill_ref = 'LT1-08';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Listing elements in A ∩ B twice when counting n(A ∪ B). The inclusion-exclusion formula subtracts the intersection exactly once to correct for this. Also confusing ∪ (union, OR) with ∩ (intersection, AND).' from public.maths_skills where skill_ref = 'LT1-08';

-- LT1-09: Area and circumference of circles
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'The circumference is the perimeter of a circle (the distance around the outside). The area is the space enclosed by the circle. Both depend on the radius r. The diameter d = 2r.' from public.maths_skills where skill_ref = 'LT1-09';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Circumference C = 2πr = πd. Area A = πr². Always use the radius (not diameter) in the area formula.' from public.maths_skills where skill_ref = 'LT1-09';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Circle with radius 7 cm: C = 2π × 7 = 14π ≈ 44.0 cm; A = π × 7² = 49π ≈ 153.9 cm². Circle with diameter 10 cm (radius 5 cm): C = 10π ≈ 31.4 cm; A = 25π ≈ 78.5 cm².' from public.maths_skills where skill_ref = 'LT1-09';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Using the diameter instead of the radius in the area formula. If given the diameter, halve it to get the radius before squaring. A = π(d/2)² = πd²/4 — do not write A = πd².' from public.maths_skills where skill_ref = 'LT1-09';

-- LT1-10: Arc length and area of sectors
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'A sector is the region between two radii and an arc (a ''pie slice''). Its arc length and area are the same fraction of the full circle''s circumference and area — the fraction being θ/360 where θ is the angle at the centre in degrees.' from public.maths_skills where skill_ref = 'LT1-10';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Arc length = (θ/360) × 2πr. Sector area = (θ/360) × πr². Perimeter of sector = arc length + 2r.' from public.maths_skills where skill_ref = 'LT1-10';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Sector with r = 8 cm and θ = 135°: arc length = (135/360) × 2π × 8 = (3/8) × 16π = 6π ≈ 18.85 cm. Sector area = (135/360) × π × 64 = (3/8) × 64π = 24π ≈ 75.40 cm². Perimeter of sector = 6π + 16 ≈ 34.85 cm.' from public.maths_skills where skill_ref = 'LT1-10';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Confusing arc length (just the curved part) with the perimeter of the sector (arc + two radii). Questions often ask for the perimeter — remember to add 2r. Also, θ must be in degrees when using θ/360.' from public.maths_skills where skill_ref = 'LT1-10';

-- LT1-11: Surface area and volume of prisms
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'A prism is a 3D shape with a uniform (unchanging) cross-section along its length. Volume is the area of the cross-section multiplied by the length. Surface area is the total area of all faces: two cross-sectional ends plus the rectangular side panels.' from public.maths_skills where skill_ref = 'LT1-11';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Volume V = A × l, where A is the cross-sectional area and l is the length. Surface area SA = 2A + P × l, where P is the perimeter of the cross-section.' from public.maths_skills where skill_ref = 'LT1-11';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Triangular prism: right-angled triangle with legs 6 cm and 8 cm (hypotenuse 10 cm), length 15 cm. Cross-sectional area = ½ × 6 × 8 = 24 cm². V = 24 × 15 = 360 cm³. SA = 2×24 + (6+8+10)×15 = 48 + 360 = 408 cm².' from public.maths_skills where skill_ref = 'LT1-11';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Forgetting to include both cross-sectional end faces in the surface area, or computing the wrong cross-sectional area (e.g. using the full rectangle height instead of the triangle area). Always identify the cross-section carefully before calculating.' from public.maths_skills where skill_ref = 'LT1-11';

-- LT1-12: Surface area and volume of cylinders
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'A cylinder has two circular ends and one curved rectangular surface. The curved surface, when unrolled, forms a rectangle with width equal to the circumference of the circle (2πr) and height equal to h.' from public.maths_skills where skill_ref = 'LT1-12';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Volume V = πr²h. Curved surface area = 2πrh. Total surface area SA = 2πr² + 2πrh = 2πr(r + h).' from public.maths_skills where skill_ref = 'LT1-12';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Cylinder with r = 4 cm and h = 9 cm: V = π × 16 × 9 = 144π ≈ 452.4 cm³. SA = 2π × 16 + 2π × 4 × 9 = 32π + 72π = 104π ≈ 326.7 cm².' from public.maths_skills where skill_ref = 'LT1-12';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Forgetting to include both circular ends in the total surface area (computing only the curved surface), or using the diameter instead of the radius in πr²h. Always check: does the question ask for curved surface area only, or total surface area?' from public.maths_skills where skill_ref = 'LT1-12';

-- ══════════════════════════════════════════════════════════════
-- LENT 2
-- ══════════════════════════════════════════════════════════════

-- LT2-01: Density and pressure
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Density measures how much mass is packed into a unit of volume. Pressure measures how much force is applied over a unit of area. Both use formula triangles: cover the quantity you want to find to see the operation needed.' from public.maths_skills where skill_ref = 'LT2-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Density D = M/V (mass ÷ volume). Pressure P = F/A (force ÷ area). Rearrangements: M = D×V, V = M/D; F = P×A, A = F/P.' from public.maths_skills where skill_ref = 'LT2-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'A metal block has mass 540 g and volume 60 cm³. Density = 540/60 = 9 g/cm³. A force of 150 N acts on an area of 0.05 m². Pressure = 150/0.05 = 3000 Pa. A box of density 2.5 g/cm³ and volume 80 cm³ has mass = 2.5 × 80 = 200 g.' from public.maths_skills where skill_ref = 'LT2-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Mixing up the formula triangle orientation — rewrite D = M/V from scratch each time rather than memorising a triangle. Also, always check units: density in g/cm³ requires mass in grams and volume in cm³; pressure in Pa (N/m²) requires force in N and area in m².' from public.maths_skills where skill_ref = 'LT2-01';

-- LT2-02: Speed, distance and time
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Speed is the rate of change of distance with time. Average speed uses the total distance and total time for the whole journey — it is not the mean of the individual speeds.' from public.maths_skills where skill_ref = 'LT2-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Speed S = D/T. Distance D = S × T. Time T = D/S.' from public.maths_skills where skill_ref = 'LT2-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'A car travels 240 km in 3 hours: speed = 240/3 = 80 km/h. How long to travel 150 km at 60 km/h? T = 150/60 = 2.5 h = 2 h 30 min. At 50 km/h for 45 minutes: D = 50 × 0.75 = 37.5 km. (Convert 45 min to 0.75 hours first.)' from public.maths_skills where skill_ref = 'LT2-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Not converting time into consistent units before substituting. If speed is in km/h, time must be in hours. 90 minutes = 1.5 hours; 45 minutes = 0.75 hours. Substituting minutes where hours are needed will give a wildly wrong answer.' from public.maths_skills where skill_ref = 'LT2-02';

-- LT2-03: Mean from a frequency table
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'For a frequency table, the mean is found by multiplying each value (or class midpoint for grouped data) by its frequency, summing all those products, and dividing by the total frequency — not by the number of rows.' from public.maths_skills where skill_ref = 'LT2-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Mean = Σ(f × x) / Σf, where f = frequency and x = value (or midpoint for grouped data).' from public.maths_skills where skill_ref = 'LT2-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Number of siblings: 0 (freq 4), 1 (freq 7), 2 (freq 5), 3 (freq 2), 4 (freq 2). Σ(fx) = 0×4 + 1×7 + 2×5 + 3×2 + 4×2 = 0+7+10+6+8 = 31. Σf = 4+7+5+2+2 = 20. Mean = 31/20 = 1.55 siblings.' from public.maths_skills where skill_ref = 'LT2-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Dividing by the number of rows in the table (5 in the example above) instead of Σf (20). The denominator must always be the total number of data points, not the number of distinct values. Also, for grouped data, use the midpoint of each class, not the upper or lower boundary.' from public.maths_skills where skill_ref = 'LT2-03';

-- LT2-04: Combined mean problems
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'When two groups with different sizes are combined, the overall mean cannot be found by simply averaging the two group means. The total sum of each group must be found (size × mean), the sums added together, and divided by the total number of items.' from public.maths_skills where skill_ref = 'LT2-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'formula', 'Combined mean = (n₁ × x̄₁ + n₂ × x̄₂) / (n₁ + n₂).' from public.maths_skills where skill_ref = 'LT2-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Class A: 12 students, mean mark 65. Class B: 18 students, mean mark 80. Total sum A = 12 × 65 = 780. Total sum B = 18 × 80 = 1440. Combined mean = (780 + 1440)/30 = 2220/30 = 74. Note: (65 + 80)/2 = 72.5 — wrong, because the groups have different sizes.' from public.maths_skills where skill_ref = 'LT2-04';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Averaging the two group means directly without weighting by group size. This only works when both groups have the same size. Always compute the total sum for each group first.' from public.maths_skills where skill_ref = 'LT2-04';

-- LT2-05: Solving linear equations
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'To solve a linear equation, perform inverse operations (in reverse BIDMAS order) to isolate the variable. When the unknown appears on both sides, collect all variable terms on one side first. Expand brackets before collecting terms.' from public.maths_skills where skill_ref = 'LT2-05';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Solve 5(2x − 3) = 3x + 9: expand → 10x − 15 = 3x + 9; collect variables → 7x = 24; divide → x = 24/7. Check: 5(48/7 − 3) = 5(27/7) = 135/7. RHS: 3(24/7) + 9 = 72/7 + 63/7 = 135/7 ✓. Solve (x+1)/3 = (2x−5)/4: cross-multiply → 4(x+1) = 3(2x−5) → 4x+4 = 6x−15 → 19 = 2x → x = 9.5.' from public.maths_skills where skill_ref = 'LT2-05';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Not expanding brackets fully before collecting terms — a common mistake is to treat 5(2x − 3) as 10x − 3. Also, sign errors when moving terms across the equals sign: adding to one side means subtracting from the other.' from public.maths_skills where skill_ref = 'LT2-05';

-- ══════════════════════════════════════════════════════════════
-- TRINITY 1
-- ══════════════════════════════════════════════════════════════

-- TR1-01: Solving simultaneous equations
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Simultaneous equations are a pair of equations with two unknowns that must be satisfied at the same time. Elimination: scale one or both equations so a variable has matching coefficients, then add or subtract to remove it. Substitution: rearrange one equation for one variable and substitute into the other.' from public.maths_skills where skill_ref = 'TR1-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Solve 3x + 2y = 16 and 5x − 2y = 8. Add the equations (y terms cancel): 8x = 24, x = 3. Substitute: 9 + 2y = 16, y = 3.5. Check: 5(3)−2(3.5) = 15−7 = 8 ✓. By substitution: from eq2, x = (8+2y)/5; substitute into eq1 and solve for y.' from public.maths_skills where skill_ref = 'TR1-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Finding only one of the two unknowns and forgetting to solve for the second. Always substitute back to find both values, and always check both answers in the original equations.' from public.maths_skills where skill_ref = 'TR1-01';

-- TR1-02: Plotting curved graphs
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'For non-linear graphs (quadratic y = ax² + bx + c, cubic y = ax³, reciprocal y = k/x), build a table of values by substituting x-values, then plot the coordinates and join with a smooth curve — never with straight lines between points.' from public.maths_skills where skill_ref = 'TR1-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Plot y = x² − 3x + 1 for −1 ≤ x ≤ 4. Table: x = −1 → y = 1+3+1 = 5; x=0 → 1; x=1 → −1; x=2 → −1; x=3 → 1; x=4 → 5. Minimum point at x = 1.5 (vertex). Join points with a smooth U-shaped curve. Roots (where y = 0) at approx x ≈ 0.38 and x ≈ 2.62.' from public.maths_skills where skill_ref = 'TR1-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Joining plotted points with straight lines instead of a smooth curve, and arithmetic errors in the table of values when x is negative (remember: (−2)² = +4, not −4). Always substitute carefully into each term separately.' from public.maths_skills where skill_ref = 'TR1-02';

-- TR1-03: Expanding triple brackets
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'To expand three brackets, expand any two of them first to get a quadratic, collect like terms, then multiply every term in the quadratic by every term in the remaining bracket. Collect like terms again. Never try to expand all three at once.' from public.maths_skills where skill_ref = 'TR1-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Expand (x + 1)(x + 2)(x − 3). Step 1: expand (x+1)(x+2) = x² + 3x + 2. Step 2: multiply by (x−3): x³ − 3x² + 3x² − 9x + 2x − 6 = x³ + 0x² − 7x − 6 = x³ − 7x + (collect: −3x²+3x² = 0) → x³ − 7x − 6. Verify by substituting x = 3: (4)(5)(0) = 0; formula: 27 − 21 − 6 = 0 ✓.' from public.maths_skills where skill_ref = 'TR1-03';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Attempting to expand all three brackets simultaneously, or not collecting like terms after the first expansion before multiplying by the third bracket. This leads to missing terms or sign errors. Always work in two clear stages and collect terms between stages.' from public.maths_skills where skill_ref = 'TR1-03';

-- ══════════════════════════════════════════════════════════════
-- TRINITY 2
-- ══════════════════════════════════════════════════════════════

-- TR2-01: Angle reasoning
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Angle reasoning uses geometric facts to find unknown angles, always with a stated reason. Key facts: angles on a straight line sum to 180°; angles at a point sum to 360°; vertically opposite angles are equal; angles in a triangle sum to 180°; corresponding angles are equal (parallel lines); alternate angles are equal (parallel lines); co-interior angles sum to 180° (parallel lines).' from public.maths_skills where skill_ref = 'TR2-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'Two parallel lines cut by a transversal. Co-interior angles are (3x + 10)° and (2x + 20)°. Co-interior angles sum to 180°: 3x + 10 + 2x + 20 = 180 → 5x + 30 = 180 → 5x = 150 → x = 30. Angles: 100° and 80°. Check: 100 + 80 = 180 ✓.' from public.maths_skills where skill_ref = 'TR2-01';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Confusing alternate angles (Z-angles, equal) with co-interior angles (C/F-angles, sum to 180°). Alternate angles are on opposite sides of the transversal; co-interior angles are on the same side. Also, exam marks require the geometric reason — not just the numerical answer.' from public.maths_skills where skill_ref = 'TR2-01';

-- TR2-02: Circle theorems
insert into public.maths_content (skill_id, content_type, content_text) select id, 'concept', 'Circle theorems are geometric facts about angles and lines in circles. The six key theorems are: (1) angle at centre = 2 × angle at circumference (same arc); (2) angles in the same segment are equal; (3) angle in a semicircle = 90°; (4) opposite angles in a cyclic quadrilateral sum to 180°; (5) tangent is perpendicular to the radius at the point of contact; (6) tangents from an external point are equal in length.' from public.maths_skills where skill_ref = 'TR2-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'worked_example', 'O is the centre of a circle. Angle AOB = 130°. Find angle ACB where C is on the major arc. Angle ACB = 130°/2 = 65° (angle at centre = twice angle at circumference). In a cyclic quadrilateral PQRS, angle P = 112°. Angle R = 180° − 112° = 68° (opposite angles sum to 180°).' from public.maths_skills where skill_ref = 'TR2-02';
insert into public.maths_content (skill_id, content_type, content_text) select id, 'common_error', 'Not quoting the circle theorem used — exam questions require the theorem to be stated by name or clearly described to earn method marks. Simply writing the angle value without a reason scores zero for the working. Also, misidentifying whether the angle is at the centre or at the circumference.' from public.maths_skills where skill_ref = 'TR2-02';
